services:
  geoipupdate:
    image: maxmindinc/geoipupdate
    container_name: zalo-geoip-update
    restart: unless-stopped
    env_file: 
      - .env.development.local
    environment:
      - GEOIPUPDATE_FREQUENCY=${GEOIPUPDATE_FREQUENCY:-168}
    volumes:
      - ./data:/usr/share/GeoIP

