// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Required by Prisma CLI commands (migrate deploy, etc.)
    // In Docker, DATABASE_URL is injected via docker-compose environment section
    url: process.env['DATABASE_URL']!,
  },
});
