import { EventType } from '@prisma/client';
import {
  VersionedDomainEvent,
  LinearVersionStrategy,
} from '@common/events/versioned-event';

/**
 * PHASE 3.4: Versioned Social/Friendship Domain Events
 *
 * R14: Type-Safe Event Contracts
 *
 * Friendship domain events with versioning support
 * Handles friend requests, acceptances, and cancellations
 *
 * Key Features:
 * - Strict TypeScript typing for all event payloads
 * - No "as any" casts in listeners (compile-time safety)
 * - Event version contracts for backward compatibility
 * - Correlation ID tracking for distributed tracing
 * - Event validation methods
 *
 * Benefits:
 * - Compile-time type checking prevents bugs
 * - IDE autocomplete for event properties
 * - Clear event contracts between services
 * - Easier to add new event types
 * - Audit trail of event schema changes
 */

// ============================================================================
// TYPE-SAFE EVENT PAYLOAD INTERFACES
// ============================================================================

/**
 * V1: Friend Request Sent Event Payload
 * Emitted when User A sends a friend request to User B
 */
export interface FriendRequestSentEventPayloadV1 {
  // Event metadata
  eventId: string; // UUID v4, generated by EventIdGenerator
  eventVersion: 1;
  eventType: 'FRIEND_REQUEST_SENT';
  correlationId?: string; // For distributed tracing
  timestamp: Date;
  
  // Domain data
  requestId: string; // FriendRequest.id
  fromUserId: string; // User A (requester)
  toUserId: string; // User B (recipient)
}

/**
 * V1: Friend Request Accepted Event Payload
 * Emitted when User B accepts a friend request from User A
 */
export interface FriendshipAcceptedEventPayloadV1 {
  eventId: string;
  eventVersion: 1;
  eventType: 'FRIEND_REQUEST_ACCEPTED';
  correlationId?: string;
  timestamp: Date;
  
  friendshipId: string; // Friendship.id
  acceptedBy: string; // User ID who accepted
  requesterId: string; // User ID who sent request
  user1Id: string; // First user in friendship
  user2Id: string; // Second user in friendship
}

/**
 * V1: Friend Request Rejected Event Payload
 * Emitted when User B declines or User A cancels a friend request
 */
export interface FriendRequestRejectedEventPayloadV1 {
  eventId: string;
  eventVersion: 1;
  eventType: 'FRIEND_REQUEST_REJECTED';
  correlationId?: string;
  timestamp: Date;
  
  requestId: string; // FriendRequest.id
  fromUserId: string; // Original requester
  toUserId: string; // Original recipient
  action: 'CANCELLED' | 'DECLINED'; // Who terminated
}

/**
 * V1: Friendship Removed Event Payload
 * Emitted when a pending friend request is cancelled
 */
export interface FriendshipRemovedEventPayloadV1 {
  eventId: string;
  eventVersion: 1;
  eventType: 'FRIEND_REQUEST_REJECTED';
  correlationId?: string;
  timestamp: Date;
  
  friendshipId: string; // Friendship.id
  cancelledBy: string; // User who cancelled
  targetUserId: string; // User who receives cancellation
}

/**
 * V1: Unfriended Event Payload
 * Emitted when an accepted friendship is terminated
 */
export interface UnfriendedEventPayloadV1 {
  eventId: string;
  eventVersion: 1;
  eventType: 'UNFRIENDED';
  correlationId?: string;
  timestamp: Date;
  
  friendshipId: string; // Friendship.id
  initiatedBy: string; // User who initiated unfriend
  user1Id: string; // First user in friendship
  user2Id: string; // Second user in friendship
}

// ============================================================================
// UNION TYPE FOR ALL EVENT PAYLOADS (enables type-safe pattern matching)
// ============================================================================

export type FriendshipEventPayload =
  | FriendRequestSentEventPayloadV1
  | FriendshipAcceptedEventPayloadV1
  | FriendRequestRejectedEventPayloadV1
  | FriendshipRemovedEventPayloadV1
  | UnfriendedEventPayloadV1;

// ============================================================================
// TYPE GUARDS FOR RUNTIME TYPE CHECKING
// ============================================================================

export function isFriendRequestSentEvent(
  event: unknown,
): event is FriendRequestSentEventPayloadV1 {
  const e = event as Record<string, unknown>;
  return (
    e &&
    e.eventType === 'FRIEND_REQUEST_SENT' &&
    typeof e.requestId === 'string' &&
    typeof e.fromUserId === 'string' &&
    typeof e.toUserId === 'string'
  );
}

export function isFriendshipAcceptedEvent(
  event: unknown,
): event is FriendshipAcceptedEventPayloadV1 {
  const e = event as Record<string, unknown>;
  return (
    e &&
    e.eventType === 'FRIEND_REQUEST_ACCEPTED' &&
    typeof e.friendshipId === 'string' &&
    typeof e.acceptedBy === 'string' &&
    typeof e.requesterId === 'string'
  );
}

export function isFriendRequestRejectedEvent(
  event: unknown,
): event is FriendRequestRejectedEventPayloadV1 {
  const e = event as Record<string, unknown>;
  return (
    e &&
    e.eventType === 'FRIEND_REQUEST_REJECTED' &&
    typeof e.requestId === 'string' &&
    (e.action === 'CANCELLED' || e.action === 'DECLINED')
  );
}

export function isUnfriendedEvent(
  event: unknown,
): event is UnfriendedEventPayloadV1 {
  const e = event as Record<string, unknown>;
  return (
    e &&
    e.eventType === 'UNFRIENDED' &&
    typeof e.friendshipId === 'string' &&
    typeof e.initiatedBy === 'string'
  );
}

// ============================================================================
// FRIEND_REQUEST_SENT EVENT
// ============================================================================

export class FriendRequestSentEvent extends VersionedDomainEvent {
  readonly version: number = 1;
  readonly eventType = EventType.FRIEND_REQUEST_SENT;

  constructor(
    readonly requestId: string,
    readonly fromUserId: string,
    readonly toUserId: string,
    readonly timestamp: Date,
    correlationId?: string,
  ) {
    super(fromUserId, 'SocialModule', 1, correlationId);
  }

  isValid(): boolean {
    return (
      super.isValid() &&
      !!this.requestId &&
      !!this.fromUserId &&
      !!this.toUserId
    );
  }

  toJSON(): Record<string, any> {
    return {
      ...super.toJSON(),
      requestId: this.requestId,
      fromUserId: this.fromUserId,
      toUserId: this.toUserId,
    };
  }
}

export class FriendRequestSentEventStrategy extends LinearVersionStrategy<FriendRequestSentEvent> {
  protected currentVersion = 1;
  protected upgradeHandlers: Record<number, (event: any) => any> = {};
  protected downgradeHandlers: Record<number, (event: any) => any> = {};
}

// ============================================================================
// FRIEND_REQUEST_ACCEPTED EVENT
// ============================================================================

export class FriendshipAcceptedEvent extends VersionedDomainEvent {
  readonly version: number = 1;
  readonly eventType = EventType.FRIEND_REQUEST_ACCEPTED;

  constructor(
    readonly friendshipId: string,
    readonly acceptedBy: string,
    readonly requesterId: string,
    readonly user1Id: string,
    readonly user2Id: string,
    correlationId?: string,
  ) {
    super(acceptedBy, 'SocialModule', 1, correlationId);
  }

  isValid(): boolean {
    return (
      super.isValid() &&
      !!this.friendshipId &&
      !!this.acceptedBy &&
      !!this.requesterId &&
      !!this.user1Id &&
      !!this.user2Id
    );
  }

  toJSON(): Record<string, any> {
    return {
      ...super.toJSON(),
      friendshipId: this.friendshipId,
      acceptedBy: this.acceptedBy,
      requesterId: this.requesterId,
      user1Id: this.user1Id,
      user2Id: this.user2Id,
    };
  }
}

export class FriendshipAcceptedEventStrategy extends LinearVersionStrategy<FriendshipAcceptedEvent> {
  protected currentVersion = 1;
  protected upgradeHandlers: Record<number, (event: any) => any> = {};
  protected downgradeHandlers: Record<number, (event: any) => any> = {};
}

// ============================================================================
// FRIEND_REQUEST_REJECTED EVENT
// ============================================================================

export class FriendRequestRejectedEvent extends VersionedDomainEvent {
  readonly version: number = 1;
  readonly eventType = EventType.FRIEND_REQUEST_REJECTED;

  constructor(
    readonly requestId: string,
    readonly fromUserId: string,
    readonly toUserId: string,
    readonly action: 'CANCELLED' | 'DECLINED',
    correlationId?: string,
  ) {
    super(fromUserId, 'SocialModule', 1, correlationId);
  }

  isValid(): boolean {
    return (
      super.isValid() &&
      !!this.requestId &&
      !!this.fromUserId &&
      !!this.toUserId &&
      ['CANCELLED', 'DECLINED'].includes(this.action)
    );
  }

  toJSON(): Record<string, any> {
    return {
      ...super.toJSON(),
      requestId: this.requestId,
      fromUserId: this.fromUserId,
      toUserId: this.toUserId,
      action: this.action,
    };
  }
}

export class FriendRequestRejectedEventStrategy extends LinearVersionStrategy<FriendRequestRejectedEvent> {
  protected currentVersion = 1;
  protected upgradeHandlers: Record<number, (event: any) => any> = {};
  protected downgradeHandlers: Record<number, (event: any) => any> = {};
}

// ============================================================================
// FRIENDSHIP_REMOVED EVENT (A cancels sent request)
// ============================================================================

export class FriendshipRemovedEvent extends VersionedDomainEvent {
  readonly version: number = 1;
  readonly eventType = EventType.FRIEND_REQUEST_REJECTED; // Reuse enum for now

  constructor(
    readonly friendshipId: string,
    readonly cancelledBy: string,
    readonly targetUserId: string,
    correlationId?: string,
  ) {
    super(cancelledBy, 'SocialModule', 1, correlationId);
  }

  isValid(): boolean {
    return (
      super.isValid() &&
      !!this.friendshipId &&
      !!this.cancelledBy &&
      !!this.targetUserId
    );
  }

  toJSON(): Record<string, any> {
    return {
      ...super.toJSON(),
      friendshipId: this.friendshipId,
      cancelledBy: this.cancelledBy,
      targetUserId: this.targetUserId,
    };
  }
}

export class FriendshipRemovedEventStrategy extends LinearVersionStrategy<FriendshipRemovedEvent> {
  protected currentVersion = 1;
  protected upgradeHandlers: Record<number, (event: any) => any> = {};
  protected downgradeHandlers: Record<number, (event: any) => any> = {};
}

// ============================================================================
// UNFRIENDED EVENT (A or B removes accepted friendship)
// ============================================================================

export class UnfriendedEvent extends VersionedDomainEvent {
  readonly version: number = 1;
  readonly eventType = EventType.UNFRIENDED;

  constructor(
    readonly friendshipId: string,
    readonly initiatedBy: string,
    readonly user1Id: string,
    readonly user2Id: string,
    correlationId?: string,
  ) {
    super(initiatedBy, 'SocialModule', 1, correlationId);
  }

  isValid(): boolean {
    return (
      super.isValid() &&
      !!this.friendshipId &&
      !!this.initiatedBy &&
      !!this.user1Id &&
      !!this.user2Id
    );
  }

  toJSON(): Record<string, any> {
    return {
      ...super.toJSON(),
      friendshipId: this.friendshipId,
      initiatedBy: this.initiatedBy,
      user1Id: this.user1Id,
      user2Id: this.user2Id,
    };
  }
}

export class UnfriendedEventStrategy extends LinearVersionStrategy<UnfriendedEvent> {
  protected currentVersion = 1;
  protected upgradeHandlers: Record<number, (event: any) => any> = {};
  protected downgradeHandlers: Record<number, (event: any) => any> = {};
}
